# Generated by Django 2.2.3 on 2020-03-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='agricultureofficers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=40)),
                ('expertise', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cropinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('croptype', models.CharField(max_length=50)),
                ('cropverities', models.CharField(max_length=1000)),
                ('temp', models.CharField(max_length=50)),
                ('rain', models.CharField(max_length=50)),
                ('soiltype', models.CharField(max_length=50)),
                ('highpro', models.CharField(max_length=1000)),
                ('majorpro', models.CharField(max_length=1000)),
                ('highprocountry', models.CharField(max_length=100)),
                ('cropimage', models.ImageField(upload_to='cropimages/')),
            ],
        ),
        migrations.CreateModel(
            name='farmersmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('adharno', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='goodspricemodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50, unique=True)),
                ('goodsprice', models.FloatField()),
                ('goodsquantity', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('goodsphoto', models.ImageField(upload_to='goods/')),
            ],
        ),
        migrations.CreateModel(
            name='oficersquerymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='schememodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=200)),
                ('schemedes', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='soilinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('state', models.CharField(max_length=1000)),
                ('rich', models.CharField(max_length=1000)),
                ('lacks', models.CharField(max_length=1000)),
                ('crops', models.CharField(max_length=1000)),
                ('simage', models.ImageField(upload_to='soilimages/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('universityname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='studentsQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=100)),
                ('universityname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uplaodvideomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.ImageField(upload_to='goods/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
